[workspace]
[package]
name = "secp256k1_program"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "secp256k1_verify"
path = "bin/verify.rs"

[[bin]]
name = "secp256k1_recover"
path = "bin/recover.rs"

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
serde = { version = "1.0.215", features = ["derive"] }
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.29.1-sp1-4.1.0", features = ["recovery", "global-context", "rand", "serde"] }

[patch.crates-io]
sp1-lib = { path = "../../../crates/zkvm/lib" }
