[package]
name = "sp1-recursion-compiler"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
p3-bn254-fr = { workspace = true }
p3-baby-bear = { workspace = true }
p3-field = { workspace = true }
p3-symmetric = { workspace = true }

sp1-core-machine = { workspace = true }
sp1-primitives = { workspace = true }
sp1-recursion-core = { workspace = true }
sp1-recursion-derive = { workspace = true }
sp1-stark = { workspace = true }

itertools = "0.13.0"
serde = { version = "1.0.204", features = ["derive"] }
backtrace = "0.3.71"
tracing = "0.1.40"
vec_map = "0.8.2"

[dev-dependencies]
p3-challenger = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
