[package]
name = "sp1-recursion-compiler"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
p3-bn254-fr = { workspace = true }
p3-baby-bear = { workspace = true }
p3-field = { workspace = true }
p3-symmetric = { workspace = true }

sp1-core-machine = { workspace = true }
sp1-primitives = { workspace = true }
sp1-recursion-core = { workspace = true }
sp1-recursion-derive = { workspace = true }
sp1-stark = { workspace = true }

itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
backtrace = { version = "0.3.71", optional = true }
tracing = { workspace = true }
vec_map = "0.8.2"

[dev-dependencies]
sp1-recursion-core = { path = "../core", features = ["program_validation"] }
p3-challenger = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }

[features]
default = ["debug"]
debug = ["sp1-recursion-core/debug", "dep:backtrace"]

[lints]
workspace = true
