[target.aarch64-unknown-linux-musl]
# Workaround for cross-compilation to ARM musl targets.
pre-build = [
  "sudo ln -s /usr/bin/g++ /usr/bin/musl-g++",
  "sudo ln -s /usr/bin/g++ /usr/bin/aarch64-linux-musl-g++"
]
