[target.aarch64-unknown-linux-musl]
# Workaround for cross-compilation to ARM musl targets.
pre-build = [
  "mkdir -p /usr/bin",
  "sudo ln -s $(which g++) /usr/bin/musl-g++",
  "sudo ln -s $(which g++) /usr/bin/aarch64-linux-musl-g++",
  "export PATH=/usr/bin:$PATH"
]
