[workspace]
# Disable git releases for all packages by default
git_release_enable = false
# Disable git tags for all packages by default
git_tag_enable = false
# Verify package build before publishing to ensure quality
publish_no_verify = false
