use std::convert::Infallible;
use std::error::Error;
use std::sync::{Arc, Mutex, MutexGuard};

use crate::zk::dot_product::{
    zk_dot_product_commitment, zk_dot_product_proof, ZkDotTotalProof, ZkVectorProverData,
};
use crate::zk::error_correcting_code::{RsFromCoefficients, RsInterpolation};
use crate::zk::hadamard_product::{
    zk_hadamard_and_dots_proof, zk_hadamard_product_commitment, ZkHadamardAndDotsTotalProof,
    ZkHadamardCommitError,
};
use derive_where::derive_where;
use rand::distributions::{Distribution, Standard};
use rand::{CryptoRng, Rng};
use serde::{Deserialize, Serialize};
use slop_algebra::AbstractField;
use slop_alloc::CpuBackend;
use slop_challenger::{CanObserve, FieldChallenger};
use slop_commit::{Message, Rounds};
use slop_merkle_tree::TensorCsProver;
use thiserror::Error;

use super::prover_transcript::ProverElement;
use super::transcript::{
    MleCommitmentIndex, PcsCommitmentEntry, Point, ProofTranscript, TranscriptLinConstraint,
    TranscriptMulConstraint,
};
use super::{
    ConstraintContextInner, ProverLinExpression, ProverValue, TranscriptIndex, ZkExpression,
    ZkMerkleizer, ZkPcsProver,
};
use super::{ExpressionIndex, ZkIopCtx};

/// A zk-proof generated by the [`ZkProverContext`] at the end of the protocol.
///
/// Should be opened to a static [`ZkCnstrProof`] and mutable [`ZkVerificationContext`] before use by verifier.
#[derive_where(Clone; P: Clone)]
#[derive(Serialize, Deserialize)]
#[serde(bound(serialize = "P: Serialize", deserialize = "P: serde::de::DeserializeOwned"))]
pub struct ZkProof<GC: ZkIopCtx, P = ()> {
    pub(in crate::zk::inner) proof: ZkCnstrProof<GC, P>,
    pub(in crate::zk::inner) transcript: ProofTranscript<GC::EF>,
    /// PCS commitment transcript: metadata for each committed MLE.
    pub(in crate::zk::inner) pcs_commitment_transcript: Vec<PcsCommitmentEntry<GC::Digest>>,
}

/// The static proof data from [`ZkProof`] needed to verify linear and multiplicative constraints.
/// The multiplicative part is optional. PCS proofs are included when PCS was used.
#[derive_where(Clone; P: Clone)]
#[derive(Serialize, Deserialize)]
#[serde(bound(serialize = "P: Serialize", deserialize = "P: serde::de::DeserializeOwned"))]
pub struct ZkCnstrProof<GC: ZkIopCtx, P = ()> {
    pub mask_commitment: GC::Digest,
    pub zk_dot_product_proof: ZkDotTotalProof<GC, RsFromCoefficients<GC::EF>>,
    pub mul_proof_wrapper: Option<ZkMulCnstrProof<GC>>,
    /// PCS proofs for each evaluation claim (empty if no PCS was used).
    pub pcs_proofs: Vec<P>,
}

/// Just the data for proving multiplicative constraints.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "", deserialize = ""))]
#[allow(clippy::type_complexity)]
pub struct ZkMulCnstrProof<GC: ZkIopCtx> {
    /// Single shared commitment for all three vectors (a, b, c)
    pub commitment: GC::Digest,
    pub mul_proof: ZkHadamardAndDotsTotalProof<GC, RsInterpolation<GC::EF>>,
}

/// Error returned by [`ZkProverContext::prove`].
///
/// The two generic parameters are the [`ZkPcsProver::ProveError`] of the PCS
/// prover in use (e.g. the stacked-basefold error or `Infallible` for the no-PCS
/// path) and the [`TensorCsProver::ProverError`] of the merkleizer in use.
#[derive(Debug, Error)]
pub enum ZkProveError<PcsErr: Error + 'static, MerkErr: Error + 'static> {
    /// MLE-eval claims were registered but `prove`/`prove_without_pcs` was called
    /// without a PCS prover.
    #[error("PCS evaluation claims exist but no PCS prover was provided")]
    NoPcsProver,
    /// Two or more eval claims targeted the same committed oracle. This breaks
    /// zero-knowledge (but not soundness) — opening one commitment at multiple
    /// points reveals more information than the masking budget covers.
    #[error(
        "multiple eval claims on the same PCS commitment (index {commitment_index}); \
         this breaks zero-knowledge but not soundness"
    )]
    DuplicateEvalClaim { commitment_index: usize },
    /// The PCS prover's `prove_multi_eval` failed.
    #[error(transparent)]
    Pcs(PcsErr),
    /// The merkleizer failed during a commit or opening — surfaces from the
    /// dot-product / Hadamard subroutines used to discharge linear and
    /// multiplicative constraints.
    #[error(transparent)]
    Merkleizer(MerkErr),
    /// A constraint subroutine was handed inputs of an inconsistent shape (e.g. the
    /// Hadamard commit's three vectors differed in length). Surfaces from the
    /// multiplicative-constraint path.
    #[error("invalid constraint input shape: {0}")]
    InvalidShape(String),
}

impl<MerkErr: Error + 'static> ZkProveError<Infallible, MerkErr> {
    /// Widens an error from the no-PCS constraint-proving path (which can never produce a
    /// [`ZkProveError::Pcs`]) into the full error type for any PCS error parameter. Total and
    /// panic-free: the `Pcs` arm is discharged via the uninhabited [`Infallible`].
    ///
    /// An inherent method rather than a `From` impl: the latter would collide with the standard
    /// library's reflexive `From<T> for T` whenever the target `PcsErr` is itself `Infallible`.
    pub fn widen<PcsErr: Error + 'static>(self) -> ZkProveError<PcsErr, MerkErr> {
        match self {
            ZkProveError::NoPcsProver => ZkProveError::NoPcsProver,
            ZkProveError::DuplicateEvalClaim { commitment_index } => {
                ZkProveError::DuplicateEvalClaim { commitment_index }
            }
            ZkProveError::Pcs(never) => match never {},
            ZkProveError::Merkleizer(e) => ZkProveError::Merkleizer(e),
            ZkProveError::InvalidShape(s) => ZkProveError::InvalidShape(s),
        }
    }
}

/// Handle to a [`ZkProverContextInner`] that provides shared mutable access.
/// This is the main type users interact with for building zero-knowledge proofs.
///
/// The handle wraps the inner context in `Arc<Mutex<>>` to allow elements
/// returned from `add_values` to hold references back to the context, while
/// remaining `Send + Sync`.
///
/// # Type Parameters
/// * `GC` - The ZK IOP context type
/// * `MK` - The merkleizer type used for tensor commitments
/// * `PD` - The PCS prover data type (defaults to `()` when no PCS is used)
///
/// Contains a challenger which can be accessed using self.challenger()
///
/// Cloning is always available (and cheap): the only field is an `Arc`, so a clone
/// is a refcount bump and does not require `PD: Clone`.
#[derive_where(Clone)]
pub struct ZkProverContext<GC: ZkIopCtx, MK: ZkMerkleizer<GC>, PD = (), P = ()> {
    inner: Arc<Mutex<ZkProverContextInner<GC, MK, PD, P>>>,
}

/// Tracks linear constraints during zero-knowledge proof generation.
/// Also tracks masking values and their dot-product commitment.
/// Consumed at the end to produce a [`ZkProof`].
#[allow(clippy::type_complexity)]
#[derive_where(Clone; <MK as TensorCsProver<GC, CpuBackend>>::ProverData: Clone, PD: Clone, P: Clone)]
pub struct ZkProverContextInner<GC: ZkIopCtx, MK: ZkMerkleizer<GC>, PD = (), P = ()> {
    /// The challenger for Fiat-Shamir (access via ZkProverContext::challenger())
    challenger: GC::Challenger,

    // transcript is represented as a jagged array, the breakpoints are the index starts of each piece
    transcript: ProofTranscript<GC::EF>,

    // Need to keep track of where in masks we are to generate the masked values
    masks: Vec<GC::EF>,
    masks_current_index: usize,

    // Linear combinations of values that need to equal 0
    // Each constraint is a vector of (coefficient, index in masked_values as a jagged array)
    lin_constraints: Vec<TranscriptLinConstraint<GC::EF>>,

    // Multiplicative constraints (if needed)
    // Each constraint is a vector of indices a,b,c where a*b=c
    mul_constraints: Option<Vec<TranscriptMulConstraint<GC::EF>>>,

    // Commitments generated on initialization
    mask_commitment: GC::Digest,
    prover_secret_data: ZkVectorProverData<
        GC,
        <MK as TensorCsProver<GC, CpuBackend>>::ProverData,
        RsFromCoefficients<GC::EF>,
    >,

    expressions: Vec<ZkExpression<GC::EF, ProverElement<GC::EF>>>,

    // PCS commitment entries with their prover data. The data is wrapped in `Option`
    // so it can be moved out (via `take_prover_data`) when the commitment is opened,
    // rather than cloned. Each commitment is opened at most once (duplicate eval
    // claims are rejected) and the data is discarded after proving, so taking is safe.
    pcs_commitments: Vec<(PcsCommitmentEntry<GC::Digest>, Option<PD>)>,

    // PCS proofs produced eagerly at each MLE-eval opening (in opening order). Moved into the
    // final `ZkCnstrProof` by `prove`.
    pcs_proofs: Vec<P>,

    // Commitments already opened, to reject a second opening of the same commitment (this would
    // break zero-knowledge). Checked at each eager opening.
    opened_commitments: std::collections::HashSet<MleCommitmentIndex>,

    // Debug: constraint debugger (only present when sp1_debug_constraints is enabled)
    #[cfg(sp1_debug_constraints)]
    debugger: crate::zk::inner::debug::ConstraintDebugger,
}

impl<GC: ZkIopCtx, MK: ZkMerkleizer<GC>, PD, P> super::constraints::private::Sealed
    for ZkProverContext<GC, MK, PD, P>
{
}

impl<GC: ZkIopCtx, MK: ZkMerkleizer<GC>, PD, P> ConstraintContextInner<GC::EF>
    for ZkProverContext<GC, MK, PD, P>
{
    type Element = ProverElement<GC::EF>;
    type Challenger = GC::Challenger;

    fn with_challenger_inner<R>(&mut self, f: impl FnOnce(&mut GC::Challenger) -> R) -> R {
        f(&mut self.borrow_mut().challenger)
    }

    fn add_lin_constraints(
        &mut self,
        constraints: impl IntoIterator<Item = TranscriptLinConstraint<GC::EF>>,
    ) {
        let mut inner = self.borrow_mut();
        let constraints: Vec<_> = constraints.into_iter().collect();
        #[cfg(sp1_debug_constraints)]
        inner.debugger.on_constraints_added(constraints.len());
        inner.lin_constraints.extend(constraints);
    }

    fn add_expr(
        &mut self,
        expr: ZkExpression<GC::EF, ProverElement<GC::EF>>,
    ) -> ProverValue<GC, MK, PD, P> {
        self.borrow_mut().expressions.push(expr);
        ExpressionIndex::new(self.borrow().expressions.len() - 1, self.clone())
    }

    fn get_expr(&self, index: usize) -> Option<ZkExpression<GC::EF, ProverElement<GC::EF>>> {
        self.borrow().expressions.get(index).cloned()
    }

    fn add_mul_constraints(
        &mut self,
        constraints: impl IntoIterator<Item = TranscriptMulConstraint<GC::EF>>,
    ) {
        let mut inner = self.borrow_mut();
        if let Some(mul_constraints) = &mut inner.mul_constraints {
            mul_constraints.extend(constraints);
        } else {
            panic!("Multiplicative constraints are not supported by this prover");
        }
    }

    #[cfg(sp1_debug_constraints)]
    fn name_last_lin_constraint_inner(&self, name: impl Into<String>) {
        self.borrow_mut().debugger.name_last(name);
    }

    fn materialize_prod(
        &mut self,
        a: ProverLinExpression<GC::EF>,
        b: ProverLinExpression<GC::EF>,
    ) -> Option<ProverElement<GC::EF>> {
        let elt = self.add_value_raw(a.value() * b.value());
        self.constrain_mul_triple(a, b, elt);
        Some(elt)
    }

    fn commitment_log_num_cols(&self, index: MleCommitmentIndex) -> usize {
        self.borrow().pcs_commitments[index.index()].0.log_num_polys
    }
}

impl<GC: ZkIopCtx, MK: ZkMerkleizer<GC>, PD, P> ZkProverContext<GC, MK, PD, P> {
    /// Lock the inner context mutably and return a guard.
    pub fn borrow_mut(&self) -> MutexGuard<'_, ZkProverContextInner<GC, MK, PD, P>> {
        self.inner.lock().expect("ZkProverContext mutex poisoned")
    }

    /// Lock the inner context and return a guard.
    pub fn borrow(&self) -> MutexGuard<'_, ZkProverContextInner<GC, MK, PD, P>> {
        self.inner.lock().expect("ZkProverContext mutex poisoned")
    }

    /// Initializes a prover that supports only linear constraints.
    ///
    /// Generates random masks, commits to them, and sets up the Fiat-Shamir challenger.
    /// Adding multiplicative constraints to the returned context will panic;
    /// use [`Self::initialize`] if multiplicative constraints are needed.
    ///
    /// # Arguments
    /// * `length` - Upper bound on the number of transcript elements that will be added.
    /// * `rng` - Cryptographically secure random number generator.
    ///
    /// # Panics
    /// Later calls will panic if more than `length` transcript elements are added.
    /// Compile with `RUSTFLAGS="--cfg sp1_debug_constraints"` to detect over-allocation.
    pub fn initialize_only_lin_constraints<RNG: CryptoRng + Rng>(
        length: usize,
        rng: &mut RNG,
    ) -> Result<Self, MK::ProverError>
    where
        Standard: Distribution<GC::EF>,
    {
        Self::initialize_inner(length, false, rng)
    }

    /// Initializes a prover that supports both linear and multiplicative constraints.
    ///
    /// Generates random masks (with extra padding for multiplicative constraint masking),
    /// commits to them, and sets up the Fiat-Shamir challenger.
    ///
    /// # Arguments
    /// * `length` - Upper bound on the number of transcript elements that will be added.
    /// * `rng` - Cryptographically secure random number generator.
    ///
    /// # Panics
    /// Later calls will panic if more than `length` transcript elements are added.
    /// Compile with `RUSTFLAGS="--cfg sp1_debug_constraints"` to detect over-allocation.
    pub fn initialize<RNG: CryptoRng + Rng>(
        length: usize,
        rng: &mut RNG,
    ) -> Result<Self, MK::ProverError>
    where
        Standard: Distribution<GC::EF>,
    {
        Self::initialize_inner(length, true, rng)
    }

    /// Shared initialization logic for both `initialize` and `initialize_only_lin_constraints`.
    fn initialize_inner<RNG: CryptoRng + Rng>(
        length: usize,
        with_mul_constraints: bool,
        rng: &mut RNG,
    ) -> Result<Self, MK::ProverError>
    where
        Standard: Distribution<GC::EF>,
    {
        let merkleizer = MK::default();
        let mut challenger = GC::default_challenger();

        // Length +1 to allow for the constant first value
        // and +6 to allow for padding to deal with multiplicative constraints (if needed)
        let mul_padding = if with_mul_constraints { 6 } else { 0 };
        let real_length = length + 1 + mul_padding;
        let masks: Vec<GC::EF> = std::iter::repeat_with(|| rng.gen()).take(real_length).collect();

        let (commitment, prover_secret_data) =
            zk_dot_product_commitment::<GC, MK, _, RsFromCoefficients<GC::EF>>(
                std::slice::from_ref(&masks),
                rng,
                &merkleizer,
            )?;

        challenger.observe(commitment);

        let mul_constraints = if with_mul_constraints { Some(vec![]) } else { None };

        let mut inner = ZkProverContextInner {
            challenger,
            transcript: ProofTranscript::new(real_length),
            masks,
            masks_current_index: 0,
            lin_constraints: vec![],
            mul_constraints,
            mask_commitment: commitment,
            prover_secret_data,
            expressions: vec![],
            pcs_commitments: vec![],
            pcs_proofs: vec![],
            opened_commitments: std::collections::HashSet::new(),
            #[cfg(sp1_debug_constraints)]
            debugger: super::debug::ConstraintDebugger::new(),
        };

        // Add a dummy constant value to allow for affine constraints
        inner.transcript.add_values(&[GC::EF::one() + inner.masks[0]]);
        inner.masks_current_index += 1;

        Ok(Self { inner: Arc::new(Mutex::new(inner)) })
    }

    fn add_values_raw(&mut self, new_values: &[GC::EF]) -> usize {
        let mut inner = self.borrow_mut();
        let masked: Vec<GC::EF> = new_values
            .iter()
            .enumerate()
            .map(|(i, &value)| value + inner.masks[inner.masks_current_index + i])
            .collect();

        let block_index = inner.transcript.next_block_index();

        inner.challenger.observe_ext_element_slice(&masked);
        inner.masks_current_index = inner.transcript.add_values(&masked);

        block_index
    }

    /// Adds new values to the proof and observes them for Fiat-Shamir.
    ///
    /// Returns the [`ExpressionIndex`]'s that these added values correspond to
    pub fn add_values(&mut self, new_values: &[GC::EF]) -> Vec<ProverValue<GC, MK, PD, P>> {
        let block_index = self.add_values_raw(new_values);
        new_values
            .iter()
            .enumerate()
            .map(|(i, &value)| {
                let elt = ProverElement::new(value, [block_index, i].into());
                self.add_expr(elt.into())
            })
            .collect()
    }

    fn add_value_raw(&mut self, value: GC::EF) -> ProverElement<GC::EF> {
        let block_index = self.add_values_raw(&[value]);
        ProverElement::new(value, [block_index, 0].into())
    }

    /// Adds a single value to the proof and observes it for Fiat-Shamir.
    ///
    /// Returns the [`ExpressionIndex`] that it corresponds to.
    pub fn add_value(&mut self, new_value: GC::EF) -> ProverValue<GC, MK, PD, P> {
        let elt = self.add_value_raw(new_value);
        self.add_expr(elt.into())
    }

    /// Returns the index of the next block to be added
    pub fn next_block_index(&self) -> usize {
        self.borrow().transcript.next_block_index()
    }

    /// Commits to a flat MLE and registers it in the context.
    ///
    /// This is the primary method for committing MLEs. It:
    /// 1. Calls the PCS prover to stack and generate the commitment
    /// 2. Observes the commitment digest in the Fiat-Shamir challenger
    /// 3. Stores the prover data for later proof generation
    ///
    /// # Arguments
    /// * `mle` — the pre-stacked data components to commit under one commitment: each `mle[i]` is a
    ///   `[2^num_encoding_variables, cols_i]` block-column tensor (column `ℓ` = a block `f_ℓ`), as
    ///   produced by [`slop_stacked::stack_multilinear`]. Their columns concatenate into the
    ///   commitment's full column set; the common case is a single component. The encoding width
    ///   (`mle[i].num_variables()`) must match the value the PCS was initialized with.
    /// * `pcs_prover` — the PCS prover for generating commitments.
    /// * `rng` — cryptographically secure random number generator.
    ///
    /// # Returns
    /// An `MleCommitmentIndex` that can be used to reference this commitment
    /// when adding evaluation claims, or an error if commitment fails.
    pub fn commit_mle<Pcs, RNG>(
        &mut self,
        mle: Message<slop_multilinear::Mle<GC::F, slop_alloc::CpuBackend>>,
        pcs_prover: &Pcs,
        rng: &mut RNG,
    ) -> Result<MleCommitmentIndex, super::ZkPcsCommitmentError>
    where
        Pcs: super::ZkPcsProver<GC, MK, ProverData = PD>,
        RNG: CryptoRng + Rng,
        Standard: Distribution<GC::F>,
    {
        // Read the stacked shape: `num_vars` is the per-column (encoding) variable count, and the
        // total number of stacked columns (a power of two) is the sum over the data components.
        let num_vars = mle[0].num_variables() as usize;
        let num_data_cols: usize = mle.iter().map(|m| m.num_polynomials()).sum();
        let log_num_polys = num_data_cols.next_power_of_two().trailing_zeros() as usize;

        // Generate commitment using the PCS prover (input is already stacked; no transpose).
        let (digest, prover_data) = pcs_prover.commit_mle(mle, rng)?;

        // Register the commitment internally
        Ok(self.register_commitment(digest, prover_data, num_vars, log_num_polys))
    }

    /// Registers a pre-committed MLE in the context.
    ///
    /// The commitment digest is observed in the Fiat-Shamir challenger.
    /// The prover data is stored internally for use during proof generation.
    ///
    /// Prefer using `commit_mle` which handles commitment generation automatically.
    /// This method is exposed for testing and advanced use cases where commitment
    /// is generated separately.
    pub(in crate::zk::inner) fn register_commitment(
        &mut self,
        digest: GC::Digest,
        prover_data: PD,
        num_vars: usize,
        log_num_polys: usize,
    ) -> MleCommitmentIndex {
        let mut inner = self.borrow_mut();

        // Observe the commitment digest in the Fiat-Shamir challenger
        inner.challenger.observe(digest);

        // Store the commitment entry with prover data
        let index = inner.pcs_commitments.len();
        let entry = PcsCommitmentEntry { digest, num_vars, log_num_polys };
        inner.pcs_commitments.push((entry, Some(prover_data)));

        MleCommitmentIndex::new(index)
    }

    /// Returns the PCS commitment entries registered so far (without prover data).
    pub fn pcs_commitments(&self) -> Vec<PcsCommitmentEntry<GC::Digest>> {
        self.borrow().pcs_commitments.iter().map(|(entry, _)| entry.clone()).collect()
    }

    /// Eagerly opens a (possibly batched) set of committed MLEs at `reduced_point`, collecting the
    /// PCS proof for [`Self::prove`] and returning the per-commitment column sub-evaluation
    /// expressions. The caller asserts how those columns combine into each claimed evaluation.
    ///
    /// The PCS opening messages are appended to the transcript (after the main-protocol values)
    /// and the Fiat-Shamir challenger advances over them, so this must only be called once the
    /// main protocol's transcript is complete — i.e. openings are terminal.
    ///
    /// Rejects a second opening of the same commitment ([`ZkProveError::DuplicateEvalClaim`]),
    /// which would break zero-knowledge.
    #[allow(clippy::type_complexity)]
    pub(in crate::zk) fn open_mle_eval<Pcs>(
        &mut self,
        pcs_prover: &Pcs,
        commitment_indices: Rounds<MleCommitmentIndex>,
        reduced_point: &Point<GC::EF>,
    ) -> Result<
        Rounds<Vec<ProverValue<GC, MK, PD, P>>>,
        ZkProveError<Pcs::ProveError, MK::ProverError>,
    >
    where
        Pcs: ZkPcsProver<GC, MK, ProverData = PD, Proof = P>,
    {
        {
            let mut inner = self.borrow_mut();
            for idx in commitment_indices.iter() {
                if !inner.opened_commitments.insert(*idx) {
                    return Err(ZkProveError::DuplicateEvalClaim { commitment_index: idx.index() });
                }
            }
        }

        let (proof, columns) = pcs_prover
            .prove_multi_eval(self, commitment_indices, reduced_point)
            .map_err(ZkProveError::Pcs)?;
        self.borrow_mut().pcs_proofs.push(proof);
        Ok(columns)
    }

    /// Moves the prover data for a given commitment index out of the context.
    ///
    /// The data is removed rather than cloned, so a second call for the same index
    /// (or an out-of-bounds index) returns `None`. This is sound because each
    /// commitment is opened at most once — duplicate eval claims are rejected by
    /// [`Self::generate_pcs_proofs`] — and the prover data is no longer needed once
    /// the commitment has been opened.
    pub fn take_prover_data(&self, index: MleCommitmentIndex) -> Option<PD> {
        self.borrow_mut().pcs_commitments.get_mut(index.index()).and_then(|(_, data)| data.take())
    }

    /// Generates a zero-knowledge dot-product proof for the constraints.
    ///
    /// Consumes the builder. Call this after all constraints and values have been added.
    /// Creates a default merkleizer internally.
    ///
    /// PCS openings are produced eagerly at each `assert_mle_eval` (see [`Self::open_mle_eval`]),
    /// so this only discharges the linear and multiplicative constraints; the eagerly-collected
    /// PCS proofs are moved into the returned [`ZkProof`].
    ///
    /// # Arguments
    /// * `rng` - Cryptographically secure random number generator
    pub fn prove<RNG>(
        mut self,
        rng: &mut RNG,
    ) -> Result<ZkProof<GC, P>, ZkProveError<Infallible, MK::ProverError>>
    where
        RNG: CryptoRng + Rng,
        Standard: Distribution<GC::EF>,
        PD: Clone,
        P: Clone,
    {
        let merkleizer = MK::default();

        // Handle multiplicative constraints
        let mul_proof = self.generate_mul_proof(&merkleizer, rng)?;

        // Debug checks
        #[cfg(sp1_debug_constraints)]
        {
            let inner = self.borrow();

            //check each linear constraint individually before RLC
            inner.debugger.check_and_report(
                &inner.transcript,
                &inner.masks,
                &inner.lin_constraints,
            );

            // Check if there were extra masks
            let structural_mask_length = if inner.mul_constraints.is_some() { 1 + 6 } else { 1 };
            if inner.masks_current_index < inner.masks.len() {
                tracing::warn!(
                    "Not all masks were used. {} non-structural masks were generated but only {} were used.",
                    inner.masks.len() - structural_mask_length,
                    inner.masks_current_index - structural_mask_length
                );
            } else {
                tracing::warn!(
                    "All masks were used. {} non-structural masks were generated and used.",
                    inner.masks.len() - structural_mask_length
                );
            }
        }

        // Dot Product proof for linear constraints
        let rlc_coeff: GC::EF = self.borrow_mut().challenger.sample_ext_element();

        let dot_vec = {
            let inner = self.borrow();
            inner.transcript.generate_rlc_dot_vector(&inner.lin_constraints, rlc_coeff)
        };

        // Extract the inner context, cloning if there are still outstanding references
        // (e.g., from ProverElement instances that haven't been dropped yet)
        let mut inner = match Arc::try_unwrap(self.inner) {
            Ok(mutex) => mutex.into_inner().expect("ZkProverContext mutex poisoned"),
            Err(arc) => {
                eprintln!(
                    "WARNING: ZkProverContext has outstanding references (likely from ProverElements or ProverConstraints). \
                     Cloning inner context. Consider dropping ProverElements before calling into_proof."
                );
                arc.lock().expect("ZkProverContext mutex poisoned").clone()
            }
        };

        let total_dot_proof = zk_dot_product_proof(
            &dot_vec,
            &inner.mask_commitment,
            inner.prover_secret_data,
            &mut inner.challenger,
            &merkleizer,
        )
        .map_err(ZkProveError::Merkleizer)?;

        // Extract just the commitment entries (without prover data) for the proof
        let pcs_commitment_transcript =
            inner.pcs_commitments.into_iter().map(|(entry, _)| entry).collect();

        Ok(ZkProof {
            proof: ZkCnstrProof {
                mask_commitment: inner.mask_commitment,
                zk_dot_product_proof: total_dot_proof,
                mul_proof_wrapper: mul_proof,
                // PCS proofs were produced eagerly at each opening, in opening order.
                pcs_proofs: inner.pcs_proofs,
            },
            transcript: inner.transcript,
            pcs_commitment_transcript,
        })
    }

    /// Helper method to generate multiplicative constraint proofs.
    fn generate_mul_proof<RNG>(
        &mut self,
        merkleizer: &MK,
        rng: &mut RNG,
    ) -> Result<Option<ZkMulCnstrProof<GC>>, ZkProveError<Infallible, MK::ProverError>>
    where
        RNG: CryptoRng + Rng,
        Standard: Distribution<GC::EF>,
    {
        if self.borrow().mul_constraints.is_none() {
            return Ok(None);
        }

        // Pad the R1CS witness used by the Hadamard check by `(r, s, rs, r-1, t, (r-1)t)`
        // for i.i.d. uniform `r, s, t`, realizing the two tautological multiplicative
        // relations `r * s = rs` and `(r-1) * t = (r-1)t`.
        //
        // Note: the simulator's bijection requires `rlc_coeff ≠ 0` and `rlc_coeff ≠ -1`
        // (where `rlc_coeff` is sampled below). We do not condition the proof on these
        // holding, so the protocol is only statistically zero-knowledge against an
        // honest verifier. Because `rlc_coeff` is derived via Fiat-Shamir from the
        // transcript hash, the verifier behaves as honest and this does not affect
        // deployment.
        let r: GC::EF = rng.gen();
        let s: GC::EF = rng.gen();
        let t: GC::EF = rng.gen();
        let r_minus_1 = r - GC::EF::one();

        let padding_block = self.next_block_index();
        self.add_values_raw(&[r, s, r * s, r_minus_1, t, r_minus_1 * t]);

        self.constrain_mul_triple(
            TranscriptIndex::<GC::EF>::from([padding_block, 0]),
            TranscriptIndex::<GC::EF>::from([padding_block, 1]),
            TranscriptIndex::<GC::EF>::from([padding_block, 2]),
        );
        self.constrain_mul_triple(
            TranscriptIndex::<GC::EF>::from([padding_block, 3]),
            TranscriptIndex::<GC::EF>::from([padding_block, 4]),
            TranscriptIndex::<GC::EF>::from([padding_block, 5]),
        );

        // Extract mul_vecs and mul_len from the inner context
        let (mul_vecs, mul_len) = {
            let inner = self.borrow();
            let mul_constraints = inner.mul_constraints.as_ref().unwrap();
            let mul_len = mul_constraints.len();

            let mut mul_vecs: [Vec<GC::EF>; 3] = [vec![], vec![], vec![]];
            for constraint in mul_constraints.iter() {
                for (i, cnstr) in constraint.0.iter().enumerate() {
                    let value = cnstr.iter().fold(GC::EF::zero(), |acc, (coeff, index)| {
                        let fi = inner.transcript.to_flat_index(index);
                        acc + *coeff * (inner.transcript.values[fi] - inner.masks[fi])
                    });
                    mul_vecs[i].push(value);
                }
            }
            (mul_vecs, mul_len)
        };

        // Commit the vectors (returns single shared commitment)
        let (commitment, prover_data) = zk_hadamard_product_commitment::<
            GC,
            MK,
            _,
            RsInterpolation<GC::EF>,
        >(
            &mul_vecs[0], &mul_vecs[1], &mul_vecs[2], rng, merkleizer
        )
        .map_err(|e| match e {
            ZkHadamardCommitError::Merkleizer(e) => ZkProveError::Merkleizer(e),
            ZkHadamardCommitError::InvalidShape(s) => ZkProveError::InvalidShape(s),
        })?;

        // Sample RLC coefficient
        let rlc_coeff: GC::EF = {
            let mut inner = self.borrow_mut();
            inner.challenger.sample_ext_element()
        };

        // Compute dot_vec from RLC powers
        let dot_vec: Vec<GC::EF> = rlc_coeff.powers().take(mul_len).collect();

        // Generate combined hadamard + dot product proofs with shared indices
        let total_mul_proof = {
            let mut inner = self.borrow_mut();
            zk_hadamard_and_dots_proof::<GC, MK, RsInterpolation<GC::EF>>(
                commitment,
                &dot_vec,
                prover_data,
                &mut inner.challenger,
                merkleizer,
            )
            .map_err(ZkProveError::Merkleizer)?
        };

        // Build and add the new linear constraints
        let new_lin_constraints = {
            let dot_prods: [GC::EF; 3] =
                std::array::from_fn(|i| total_mul_proof.dot_claimed_dot_products()[i]);
            let inner = self.borrow();
            let mul_constraints = inner.mul_constraints.as_ref().unwrap();
            inner.transcript.pickout_lin_constraints_from_mul_constraints(
                mul_constraints,
                &dot_prods,
                rlc_coeff,
            )
        };

        self.add_lin_constraints(new_lin_constraints.to_vec());

        Ok(Some(ZkMulCnstrProof { commitment, mul_proof: total_mul_proof }))
    }
}
