[workspace]
[package]
name = "bls12_381_test_program"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bls12_381_fp_test_inverse"
path = "bin/test_inverse.rs"

[[bin]]
name = "bls12_381_fp_test_sqrt"
path = "bin/test_sqrt.rs"

[[bin]]
name = "bls12_381_fp2_test_inverse"
path = "bin/test_inverse_fp2.rs"

[[bin]]
name = "bls12_381_fp2_test_sqrt"
path = "bin/test_sqrt_fp2.rs"

[[bin]]
name = "bls12_381_ec_add_test"
path = "bin/test_bls_add.rs"

[[bin]]
name = "bls12_381_ec_double_test"
path = "bin/test_bls_double.rs"

# todo explicit mul and add tests

[dependencies]
sp1-lib = { path = "../../../crates/zkvm/lib" }
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381", tag = "patch-0.8.0-sp1-5.0.0", features = ["groups"] }

[patch.crates-io]
sp1-lib = { path = "../../../crates/zkvm/lib" }
