[workspace]
[package]
name = "curve25519-dalek"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ed25519_verify"
path = "bin/verify.rs"

[[bin]]
name = "curve25519_decompress"
path = "bin/decompress.rs"

[[bin]]
name = "curve25519_add_then_multiply"
path = "bin/add_then_multiply.rs"

[[bin]]
name = "curve25519_zero_msm"
path = "bin/zero_msm.rs"

[[bin]]
name = "curve25519_zero_mul"
path = "bin/zero_mul.rs"

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
ed25519-dalek = { version = "2.1.0", features = ["alloc", "serde"] }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "serde"] }

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek", tag = "patch-4.1.3-sp1-5.0.0" }
# Temporarily pinning to a specific version of ed25519-dalek to avoid a build failure
sp1-lib = { path = "../../../crates/zkvm/lib" }
