use std::path::{Path, PathBuf};
use std::{env, fs};

use slop_algebra::PrimeField32;
use slop_bn254::{bn254_internal_diagonal, bn254_montgomery_limbs, bn254_poseidon2_rc3};
use slop_koala_bear::{
    KoalaBear_BEGIN_EXT_CONSTS, KoalaBear_END_EXT_CONSTS, KoalaBear_PARTIAL_CONSTS,
};

fn cbindgen_builder() -> cbindgen::Builder {
    /// The warning placed in the cbindgen header.
    const AUTOGEN_WARNING: &str =
        "/* Automatically generated by `cbindgen`. Not intended for manual editing. */";

    // Generate a header containing bindings to the crate.
    cbindgen::Builder::new()
        .with_pragma_once(true)
        .with_autogen_warning(AUTOGEN_WARNING)
        .with_no_includes()
        .with_sys_include("cstdint")
        .with_parse_deps(true)
        .with_parse_include(&[
            "sp1-hypercube",
            "sp1-primitives",
            "p3-koala-bear",
            "sp1-core-machine",
            "slop-koala-bear",
            "sp1-core-executor",
            "sp1-recursion-executor",
            "sp1-recursion-machine",
        ])
        .with_parse_extra_bindings(&[
            "sp1-hypercube",
            "p3-koala-bear",
            "slop-koala-bear",
            "sp1-recursion-executor",
            "sp1-recursion-machine",
            "sp1-core-machine",
        ])
        .rename_item("KoalaBear", "KoalaBearP3")
        .include_item("GlobalInteractionEvent")
        .include_item("GlobalCols")
        .include_item("MemoryAccessColsChips")
        .include_item("Poseidon2Instr")
        .include_item("Poseidon2PreprocessedColsWide")
        .include_item("Poseidon2Event")
        .include_item("SelectInstr")
        .include_item("SelectPreprocessedCols")
        .include_item("SelectEvent")
        .include_item("SelectCols")
        .include_item("BaseAluInstr")
        .include_item("BaseAluAccessCols")
        .include_item("BaseAluEvent")
        .include_item("BaseAluValueCols")
        .include_item("ExtAluInstr")
        .include_item("ExtAluAccessCols")
        .include_item("ExtAluEvent")
        .include_item("ExtAluValueCols")
        .include_item("ExtFeltInstr")
        .include_item("ExtFeltEvent")
        .include_item("ConvertAccessCols")
        .include_item("ConvertValueCols")
        .include_item("Poseidon2LinearLayerAccessCols")
        .include_item("Poseidon2LinearLayerValueCols")
        .include_item("Poseidon2LinearLayerInstr")
        .include_item("Poseidon2SBoxInstr")
        .include_item("Poseidon2SBoxIo")
        .include_item("Poseidon2SBoxAccessCols")
        .include_item("Poseidon2SBoxValueCols")
        .include_item("NUM_CONVERT_ENTRIES_PER_ROW")
        .include_item("NUM_LINEAR_ENTRIES_PER_ROW")
        .include_item("NUM_SBOX_ENTRIES_PER_ROW")
        .include_item("PERMUTATION_WIDTH")
        .include_item("PrefixSumChecksEvent")
        .include_item("PrefixSumChecksCols")
        .with_namespace("sp1_gpu_sys")
        .with_crate(env::var("CARGO_MANIFEST_DIR").unwrap())
}

/// Place a relative symlink pointing to `original` at `link`.
fn rel_symlink_file<P, Q>(original: P, link: Q)
where
    P: AsRef<std::path::Path>,
    Q: AsRef<std::path::Path>,
{
    #[cfg(unix)]
    use std::os::unix::fs::symlink;
    #[cfg(windows)]
    use std::os::windows::fs::symlink_file as symlink;

    let target_dir = link.as_ref().parent().unwrap();
    fs::create_dir_all(target_dir).unwrap();
    let _ = fs::remove_file(&link);
    let relpath = pathdiff::diff_paths(original, target_dir).unwrap();
    symlink(relpath, link).unwrap();
}

/// Check if CUDA is available on this system.
fn detect_cuda() -> bool {
    // Track rerun-if-env-changed for the explicit override
    println!("cargo:rerun-if-env-changed=SP1_CUDA_ENABLED");

    // 1. Check explicit SP1_CUDA_ENABLED env var
    if let Ok(val) = env::var("SP1_CUDA_ENABLED") {
        match val.to_lowercase().as_str() {
            "0" | "false" => return false,
            "1" | "true" => return true,
            _ => {} // Fall through to auto-detection
        }
    }

    // 2. Try running nvcc --version
    if std::process::Command::new("nvcc")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
    {
        return true;
    }

    // 3. Check CUDA_PATH env var
    if env::var("CUDA_PATH").is_ok() {
        return true;
    }

    // 4. Check common CUDA installation paths
    if std::path::Path::new("/usr/local/cuda/bin/nvcc").exists() {
        return true;
    }
    if std::path::Path::new("/opt/cuda/bin/nvcc").exists() {
        return true;
    }

    false
}

/// The CUDA headers holding the Poseidon2 round constants, relative to the crate root.
const KB31_HEADER: &str = "include/poseidon2/poseidon2_kb31_16.cuh";
const BN254_HEADER: &str = "include/poseidon2/poseidon2_bn254_3.cuh";

/// Pull the integer literals out of every `ctor(...)` initializer in the `__constant__` table
/// declared as `decl`, one inner `Vec` per table entry.
///
/// Neither header nests braces inside one of these initializer lists, so the first `}` after the
/// declaration is its terminator.
fn parse_table(header: &str, path: &str, ctor: &str, decl: &str) -> Vec<Vec<u32>> {
    let body =
        header.split_once(decl).unwrap_or_else(|| panic!("{path}: no declaration of `{decl}`")).1;
    let end =
        body.find('}').unwrap_or_else(|| panic!("{path}: `{decl}` initializer is unterminated"));
    body[..end]
        .split(&format!("{ctor}("))
        .skip(1)
        .map(|tail| {
            let inner = tail
                .split_once(')')
                .unwrap_or_else(|| panic!("{path}: `{decl}` has an unclosed `{ctor}(`"))
                .0;
            assert!(
                inner.chars().all(|c| c.is_ascii_digit() || c.is_whitespace() || c == ','),
                "{path}: `{decl}` has a non-literal entry at `{ctor}({inner:.32}`"
            );
            inner
                .split(|c: char| !c.is_ascii_digit())
                .filter(|run| !run.is_empty())
                .map(|run| {
                    run.parse().unwrap_or_else(|_| {
                        panic!("{path}: `{decl}` has an out-of-range literal `{run}`")
                    })
                })
                .collect()
        })
        .collect()
}

/// Compare one parsed CUDA table against the values this workspace derives for it.
fn compare_table(path: &str, name: &str, found: &[Vec<u32>], expected: &[Vec<u32>]) {
    assert_eq!(
        found.len(),
        expected.len(),
        "{path}: {name} has {} entries, but Rust supplies {}",
        found.len(),
        expected.len()
    );
    for (i, (cuda, rust)) in found.iter().zip(expected).enumerate() {
        assert_eq!(
            cuda, rust,
            "{path}: {name}[{i}] is {cuda:?}, but Rust has {rust:?}. The CUDA and Rust Poseidon2 \
             constants have drifted; fix whichever side changed."
        );
    }
}

/// Guard the CUDA copies of the Poseidon2 constants against drifting from the Rust ones.
///
/// Both headers hand-copy constants this workspace already derives, ordered as the kernel walks
/// them (beginning external, ending external, internal) and bound directly by `StaticHasher` in
/// `poseidon2.cuh`. Only what is read is checked, and that differs between the two headers even
/// where they declare the same names; each function below says which of its tables are live.
///
/// A build script rather than a test: CPU CI excludes `sp1-gpu-*` from `cargo test` and a test
/// binary here cannot link without CUDA, but build scripts still run under `cargo check`.
fn check_poseidon2_constants(crate_dir: &Path) {
    check_kb31_constants(crate_dir);
    check_bn254_constants(crate_dir);
}

/// The KoalaBear table holds canonical values, so entries compare against `as_canonical_u32()`
/// rather than `KoalaBear`'s inner Montgomery value.
///
/// That follows from overload resolution: `kb31_t(uint32_t)` stores its argument raw while
/// `kb31_t(int)` converts with `(a << 32) % MOD`, and a decimal literal below `INT_MAX` is `int`.
/// Every canonical value is below `MOD` (0x7f000001), so these bind the converting one. `bn254_t`'s
/// only matching constructor copies limbs verbatim instead.
///
/// `MAT_INTERNAL_DIAG_M1` and `MONTY_INVERSE` are not checked: this header reads neither, applying
/// the diagonal as shifts against a hardcoded `SH` table. `SH` is live and unchecked, the same
/// exposure in a different table. The BN254 header does read its diagonal; see
/// `check_bn254_constants`.
fn check_kb31_constants(crate_dir: &Path) {
    let path = crate_dir.join(KB31_HEADER);
    let header = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

    let external: Vec<Vec<u32>> = KoalaBear_BEGIN_EXT_CONSTS
        .iter()
        .chain(KoalaBear_END_EXT_CONSTS.iter())
        .flat_map(|round| round.iter().map(|c| vec![c.as_canonical_u32()]))
        .collect();
    let internal: Vec<Vec<u32>> =
        KoalaBear_PARTIAL_CONSTS.iter().map(|c| vec![c.as_canonical_u32()]).collect();

    for (name, decl, expected) in [
        ("EXTERNAL_ROUND_CONSTANTS", "EXTERNAL_ROUND_CONSTANTS[ROUNDS_F * WIDTH]", external),
        ("INTERNAL_ROUND_CONSTANTS", "INTERNAL_ROUND_CONSTANTS[ROUNDS_P]", internal),
    ] {
        let found = parse_table(&header, KB31_HEADER, "kb31_t", decl);
        compare_table(KB31_HEADER, name, &found, &expected);
    }
}

/// The BN254 table is written in Montgomery form, eight little-endian `uint32_t` limbs per constant,
/// so the comparison goes through `bn254_montgomery_limbs`. `bn254_t` is `mont_t<...>`, whose
/// eight-argument constructor assigns into `even[0..8]` with no conversion, so the header text is
/// already the stored representation.
///
/// `bn254_poseidon2_rc3` returns all 64 rounds in Plonky3's flat order; the split below is
/// `outer_perm`'s, and the kernel's begin-then-end external layout is that split concatenated.
///
/// `MAT_INTERNAL_DIAG_M1` is checked here though the KoalaBear one is not, and the headers looking
/// parallel is the trap. `Bn254::internalLinearLayer` ignores its parameters but has no shift path:
/// it multiplies lane `i` by the class constant on all 56 internal rounds. `bn254_internal_diagonal`
/// reads that diagonal back out of `DiffusionMatrixBN254`, so the comparison is against CPU
/// behaviour rather than a third transcription.
///
/// `MONTY_INVERSE` is unchecked in both headers; the only mentions are the two
/// `internalLinearLayer` call sites, passing it into a parameter neither implementation names.
fn check_bn254_constants(crate_dir: &Path) {
    /// Full rounds, half at the start of the permutation and half at the end.
    const ROUNDS_F: usize = 8;
    /// Partial rounds, sitting between the two halves.
    const ROUNDS_P: usize = 56;

    let path = crate_dir.join(BN254_HEADER);
    let header = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

    let rounds = bn254_poseidon2_rc3();
    assert_eq!(
        rounds.len(),
        ROUNDS_F + ROUNDS_P,
        "slop-bn254 supplies {} rounds, but {BN254_HEADER} is built for {}",
        rounds.len(),
        ROUNDS_F + ROUNDS_P
    );
    let internal_start = ROUNDS_F / 2;
    let internal_end = internal_start + ROUNDS_P;

    let external: Vec<Vec<u32>> = rounds[..internal_start]
        .iter()
        .chain(&rounds[internal_end..])
        .flat_map(|round| round.iter().map(|c| bn254_montgomery_limbs(*c).to_vec()))
        .collect();
    let internal: Vec<Vec<u32>> = rounds[internal_start..internal_end]
        .iter()
        .map(|round| bn254_montgomery_limbs(round[0]).to_vec())
        .collect();
    let diagonal: Vec<Vec<u32>> =
        bn254_internal_diagonal().iter().map(|d| bn254_montgomery_limbs(*d).to_vec()).collect();

    for (name, decl, expected) in [
        ("EXTERNAL_ROUND_CONSTANTS", "EXTERNAL_ROUND_CONSTANTS[ROUNDS_F * WIDTH]", external),
        ("INTERNAL_ROUND_CONSTANTS", "INTERNAL_ROUND_CONSTANTS[ROUNDS_P]", internal),
        ("MAT_INTERNAL_DIAG_M1", "MAT_INTERNAL_DIAG_M1[WIDTH]", diagonal),
    ] {
        let found = parse_table(&header, BN254_HEADER, "bn254_t", decl);
        compare_table(BN254_HEADER, name, &found, &expected);
    }
}

fn main() {
    // Directives for tracking changes in folders
    println!("cargo:rerun-if-changed=include/");
    println!("cargo:rerun-if-changed=lib/");
    println!("cargo:rerun-if-changed=sppark/");
    println!("cargo:rerun-if-changed=CMakeLists.txt");
    // Directives for tracking changes in compilation profiles
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=OPT_LEVEL");
    println!("cargo:rerun-if-env-changed=DEBUG");
    println!("cargo:rerun-if-env-changed=CUDA_ARCHS");
    println!("cargo:rerun-if-env-changed=PROFILE_DEBUG_DATA");

    // The crate directory.
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Fail fast if the CUDA copy of the Poseidon2 round constants has drifted from the
    // Rust one. Ahead of everything below so it still runs where nvcc is absent.
    check_poseidon2_constants(&crate_dir);

    // The output directory, where built artifacts should be placed.
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // The directory to place headers into.
    let out_include_dir = out_dir.join("include");
    const INCLUDE_DIRNAME: &str = "include";

    // Generate cbindgen headers BEFORE building with CMake
    let cbindgen_hpp = "sp1-gpu-cbindgen.hpp";
    let header_path = out_include_dir.join(cbindgen_hpp);

    match cbindgen_builder().generate() {
        Ok(bindings) => {
            fs::create_dir_all(&out_include_dir).unwrap();
            if bindings.write_to_file(&header_path) {
                // Symlink header into `target/include` for IDE purposes
                let mut dir = out_dir.clone();
                while !dir.ends_with("target") {
                    if !dir.pop() {
                        break;
                    }
                }
                if dir.ends_with("target") {
                    rel_symlink_file(&header_path, dir.join(INCLUDE_DIRNAME).join(cbindgen_hpp));
                }
            }
        }
        Err(cbindgen::Error::ParseSyntaxError { .. }) => {
            // Ignore parse errors in the build script.
            // We let rust-analyzer/rustc run to report the syntax error with diagnostics.
            return;
        }
        Err(e) => panic!("{e:?}"),
    }

    // Check if CUDA is available before attempting to build
    if !detect_cuda() {
        println!("cargo:warning=CUDA not detected, skipping GPU build");
        return;
    }

    // Build using CMake
    let mut cmake_config = cmake::Config::new(".");

    // Export compile commands for clangd IDE support
    cmake_config.define("CMAKE_EXPORT_COMPILE_COMMANDS", "ON");

    // Pass CUDA architectures to CMake only if explicitly set
    // Otherwise, CMake will use its own version-based defaults
    if let Ok(cuda_archs) = env::var("CUDA_ARCHS") {
        cmake_config.define("CUDA_ARCHS", &cuda_archs);
    }

    // Pass cbindgen include directory
    cmake_config.define("CBINDGEN_INCLUDE_DIR", out_include_dir.display().to_string());

    // Pass profile debug flag if set
    if let Some(profile_debug_data) = env::var_os("PROFILE_DEBUG_DATA") {
        if profile_debug_data == "true" {
            cmake_config.define("PROFILE_DEBUG_DATA", "true");
        }
    }

    // Determine build type based on profile
    let profile = env::var("PROFILE").unwrap_or_else(|_| "release".to_string());
    if profile == "debug" {
        cmake_config.profile("Debug");
    } else {
        cmake_config.profile("Release");
    }

    // Build via CMake
    let dst = cmake_config.build();

    // Symlink compile_commands.json to project root for clangd
    let compile_commands_src = dst.join("build").join("compile_commands.json");
    if compile_commands_src.exists() {
        let project_root = crate_dir.join("../..").canonicalize().unwrap();
        rel_symlink_file(&compile_commands_src, project_root.join("compile_commands.json"));
    }

    // Link the library
    println!("cargo:rustc-link-search=native={}/lib", dst.display());
    println!("cargo:rustc-link-lib=static=sys-cuda");

    // Add CUDA library search paths. Track the env var so switching
    // `CUDA_PATH` re-emits the link-search lines — otherwise a stale cached
    // path (e.g. `/usr/local/cuda` pointing at a newer toolkit than nvcc)
    // fails to link with undefined cudart symbols.
    println!("cargo:rerun-if-env-changed=CUDA_PATH");
    if let Ok(cuda_path) = env::var("CUDA_PATH") {
        println!("cargo:rustc-link-search=native={cuda_path}/lib64");
        println!("cargo:rustc-link-search=native={cuda_path}/lib");
    } else {
        println!("cargo:rustc-link-search=native=/usr/local/cuda/lib64");
    }

    // Link CUDA runtime libraries
    println!("cargo:rustc-link-lib=cudart");
    println!("cargo:rustc-link-lib=cudadevrt");

    // Link system libraries
    println!("cargo:rustc-link-lib=stdc++");
    println!("cargo:rustc-link-lib=gomp");
    println!("cargo:rustc-link-lib=dl");

    // Add include directories for compilation if needed
    println!("cargo:include={}", out_include_dir.display());
}
