[package]
name = "u256x2048-mul"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
sp1-derive = { path = "../../../../crates/derive" }
num-bigint = "0.4.6"
num = { version = "0.4.1" }
rand = "0.8.5"
bytemuck = "1.15.0"