// This file is auto-generated by sp1-recursion-compiler.
package verifier

import (
	"github.com/consensys/gnark/frontend"
)

type Circuit struct {
	X frontend.Variable
	Y frontend.Variable
}

func (circuit *Circuit) Define(api frontend.API) error {

	// Variables.
	var var0 frontend.Variable
	var var1 frontend.Variable

	// Operations.
	var0 = frontend.Variable(0)
	var1 = frontend.Variable(0)
	api.AssertIsEqual(var0, var1)
	return nil
}
