//! Generate the soundcalc SP1 TOML config from SP1.
//!
//! Run with:
//!   cargo run --release -p sp1-prover --bin gen_soundcalc_toml -- --output <path>

use std::path::PathBuf;

use clap::Parser;
use slop_air::BaseAir;
use slop_algebra::Field;
use slop_basefold::BATCH_GRINDING_BITS;
use sp1_core_executor::ELEMENT_THRESHOLD;
use sp1_core_machine::riscv::RiscvAir;
use sp1_hypercube::{air::MachineAir, Machine, GKR_GRINDING_BITS, MAX_CONSTRAINT_DEGREE};
use sp1_primitives::{
    fri_params::{
        unique_decoding_queries, CORE_LOG_BLOWUP, RECURSION_LOG_BLOWUP, SP1_PROOF_OF_WORK_BITS,
    },
    SP1Field,
};
use sp1_prover::{
    CompressAir, CORE_LOG_STACKING_HEIGHT, CORE_MAX_LOG_ROW_COUNT, RECURSION_LOG_TRACE_AREA,
};
use sp1_verifier::compressed::{RECURSION_LOG_STACKING_HEIGHT, RECURSION_MAX_LOG_ROW_COUNT};
use tracing_subscriber::EnvFilter;

const SP1_VERSION: &str = env!("CARGO_PKG_VERSION");
const DEFAULT_OUTPUT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/sp1.toml");

#[derive(Parser)]
#[command(
    about = "Generate soundcalc TOML file from SP1",
    long_about = None,
)]
struct Args {
    #[arg(short, long, default_value = DEFAULT_OUTPUT)]
    output: PathBuf,
}

struct CircuitData {
    trace_columns: usize,
    num_constraints: usize,
    num_lookups_m: usize,
    num_columns_s: usize,
}

fn get_circuit_data<F: Field, A>(machine: Machine<F, A>) -> CircuitData
where
    A: sp1_hypercube::air::MachineAir<F>,
{
    let mut max_cols = 0usize;
    let mut max_constr = 0usize;
    let mut max_inter = 0usize;
    for cluster in &machine.shape().chip_clusters {
        let mut cols = 0usize;
        let mut constr = 0usize;
        let mut inter = 0usize;
        for chip in cluster {
            constr += chip.num_constraints;
            cols += chip.preprocessed_width() + chip.width();
            inter += chip.receives().len() + chip.sends().len();
        }
        max_cols = max_cols.max(cols);
        max_constr = max_constr.max(constr);
        max_inter = max_inter.max(inter);
    }
    let max_values_len = machine
        .chips()
        .iter()
        .flat_map(|chip| chip.receives().iter().chain(chip.sends().iter()))
        .map(|interaction| interaction.values.len())
        .max()
        .unwrap_or(0);
    CircuitData {
        trace_columns: max_cols,
        num_constraints: max_constr,
        num_lookups_m: max_inter,
        num_columns_s: max_values_len + 1,
    }
}

fn folding_factors(log_stacking_height: u32) -> String {
    let items = std::iter::repeat_n("2", log_stacking_height as usize).collect::<Vec<_>>();
    format!("[{}]", items.join(", "))
}

fn format_rho(blowup_factor: u32) -> String {
    let rho = 1.0_f64 / f64::from(blowup_factor);
    let s = format!("{rho}");
    if s.contains('.') {
        s
    } else {
        format!("{s}.0")
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let args = Args::parse();

    let core = get_circuit_data(RiscvAir::<SP1Field>::machine());
    let compress = get_circuit_data(CompressAir::<SP1Field>::compress_machine());

    let core_blowup = 1u32 << CORE_LOG_BLOWUP;
    let recursion_blowup = 1u32 << RECURSION_LOG_BLOWUP;
    let core_trace_len: u64 = 1u64 << CORE_MAX_LOG_ROW_COUNT;
    let recursion_trace_len: u64 = 1u64 << RECURSION_MAX_LOG_ROW_COUNT;
    let core_dense_len: u64 = 1u64 << CORE_LOG_STACKING_HEIGHT;
    let recursion_dense_len: u64 = 1u64 << RECURSION_LOG_STACKING_HEIGHT;
    let core_queries = unique_decoding_queries(CORE_LOG_BLOWUP);
    let recursion_queries = unique_decoding_queries(RECURSION_LOG_BLOWUP);
    let core_rho = format_rho(core_blowup);
    let recursion_rho = format_rho(recursion_blowup);
    let core_folding = folding_factors(CORE_LOG_STACKING_HEIGHT);
    let recursion_folding = folding_factors(RECURSION_LOG_STACKING_HEIGHT);
    let core_dense_batch: u64 = ELEMENT_THRESHOLD / (1u64 << CORE_LOG_STACKING_HEIGHT) + 1;
    let recursion_dense_batch: u64 =
        (1u64 << RECURSION_LOG_TRACE_AREA) / (1u64 << RECURSION_LOG_STACKING_HEIGHT);

    let toml = format!(
        "\
# SP1 Hypercube VM Configuration
# Auto-generated by `cargo run --release -p sp1-prover --bin gen_soundcalc_toml`.

[zkevm]
name = \"SP1\"
protocol_family = \"JAGGED\"
field = \"KoalaBear^4\"
version = \"{SP1_VERSION}\"
hash_size_bits = 248

[[circuits]]
name = \"core\"
udr_only = true
blowup_factor = {core_blowup}
rho = {core_rho}
trace_length = {core_trace_len} # 2^{CORE_MAX_LOG_ROW_COUNT}
trace_columns = {core_trace_columns}
dense_length = {core_dense_len} # 2^{CORE_LOG_STACKING_HEIGHT}
dense_batch = {core_dense_batch}
num_constraints = {core_num_constraints}
air_max_degree = {MAX_CONSTRAINT_DEGREE}
# SP1 has no \"next row\" constraints.
opening_points = 1
# We batch using the random `eq` polynomials.
power_batching = false
multilinear_batching = true
multilinear_zerocheck = true
num_queries = {core_queries}
fri_folding_factors = {core_folding}
fri_early_stop_degree = {core_blowup}
grinding_batching_phase = {BATCH_GRINDING_BITS}
grinding_query_phase = {SP1_PROOF_OF_WORK_BITS}

[[circuits.lookups]]
name = \"lookup\"
logup_type = \"multivariate\"
rows_L = {core_trace_len}
rows_T = 0
num_columns_S = {core_num_columns_s}
num_lookups_M = {core_num_lookups_m}
grinding_bits_lookup = {GKR_GRINDING_BITS}
multilinear_fingerprint = true


[[circuits]]
name = \"compress\"
udr_only = true
blowup_factor = {recursion_blowup}
rho = {recursion_rho}
trace_length = {recursion_trace_len} # 2^{RECURSION_MAX_LOG_ROW_COUNT}
trace_columns = {recursion_trace_columns}
dense_length = {recursion_dense_len} # 2^{RECURSION_LOG_STACKING_HEIGHT}
dense_batch = {recursion_dense_batch}
num_constraints = {recursion_num_constraints}
air_max_degree = {MAX_CONSTRAINT_DEGREE}
# SP1 has no \"next row\" constraints.
opening_points = 1
# We batch using the random `eq` polynomials.
power_batching = false
multilinear_batching = true
multilinear_zerocheck = true
num_queries = {recursion_queries}
fri_folding_factors = {recursion_folding}
fri_early_stop_degree = {recursion_blowup}
grinding_batching_phase = {BATCH_GRINDING_BITS}
grinding_query_phase = {SP1_PROOF_OF_WORK_BITS}

[[circuits.lookups]]
name = \"lookup\"
logup_type = \"multivariate\"
rows_L = {recursion_trace_len}
rows_T = 0
num_columns_S = {recursion_num_columns_s}
num_lookups_M = {recursion_num_lookups_m}
grinding_bits_lookup = {GKR_GRINDING_BITS}
multilinear_fingerprint = true
",
        core_trace_columns = core.trace_columns,
        core_num_constraints = core.num_constraints,
        core_num_lookups_m = core.num_lookups_m,
        core_num_columns_s = core.num_columns_s,
        recursion_trace_columns = compress.trace_columns,
        recursion_num_constraints = compress.num_constraints,
        recursion_num_lookups_m = compress.num_lookups_m,
        recursion_num_columns_s = compress.num_columns_s,
    );

    if let Some(parent) = args.output.parent() {
        std::fs::create_dir_all(parent).expect("create output dir");
    }
    std::fs::write(&args.output, toml).expect("write toml");
    tracing::info!("wrote {}", args.output.display());
}
