[package]
name = "bls12381-double-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
num = { version = "0.4.1", default-features = false }
