[package]
name = "rand-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
sp1-derive = { path = "../../../../crates/derive" }
rand = "0.8.5"
