use std::{
    collections::{BTreeMap, HashMap, HashSet},
    sync::{Arc, Mutex},
};

use itertools::Itertools;
use powdr_autoprecompiles::{
    blocks::PcStep,
    expression::{AlgebraicExpression, AlgebraicReference},
    Substitution,
};
use powdr_expression::{AlgebraicBinaryOperator, AlgebraicUnaryOperator};
use slop_air::{Air, AirBuilder, BaseAir, PairBuilder};
use slop_algebra::PrimeField32;
use slop_matrix::Matrix;
use slop_maybe_rayon::prelude::{
    IndexedParallelIterator, IntoParallelIterator, ParallelIterator, ParallelSliceMut,
};
use sp1_core_executor::{
    events::ByteLookupEvent, opcode::ByteOpcode, ApcRange, ExecutionRecord, Program, RiscvAirId,
    SP1CoreOpts, SupervisorMode, TracingVM,
};
use sp1_hypercube::{
    air::{AirInteraction, InteractionScope, MachineAir, MessageBuilder, SP1AirBuilder},
    InteractionKind, Machine,
};

use crate::{
    autoprecompiles::{
        instruction::Sp1Instruction,
        instruction_handler::{try_instruction_type_to_air_id, InstructionType},
        Sp1Apc,
    },
    riscv::RiscvAir,
    utils::{next_multiple_of_32, zeroed_f_vec},
};

#[derive(Debug)]
struct CachedApc<F: PrimeField32> {
    /// The APC
    apc: Arc<Sp1Apc<F>>,
    /// The cached columns of the APC.
    columns: Vec<AlgebraicReference>,
}

impl<F: PrimeField32> CachedApc<F> {
    /// The width of the APC.
    pub fn width(&self) -> usize {
        self.columns.len()
    }
}

impl<F: PrimeField32> From<Arc<Sp1Apc<F>>> for CachedApc<F> {
    fn from(apc: Arc<Sp1Apc<F>>) -> Self {
        let columns = apc.machine.main_columns().collect();
        Self { apc, columns }
    }
}

/// Key identifying the shard record a cached trace belongs to: `(proof_nonce, initial_timestamp)`.
/// Distinct per shard, so concurrent shard workers sharing this `Arc<ApcChip>` don't collide.
fn record_key(record: &ExecutionRecord) -> ([u32; 4], u64) {
    (record.public_values.proof_nonce, record.initial_timestamp)
}

#[derive(Debug)]
pub struct ApcChip<F: PrimeField32> {
    /// The ID of the APC.
    id: usize,
    /// The name of this APC
    name: String,
    /// The cached APC.
    cached_apc: CachedApc<F>,
    /// A machine to generate traces for the APC. By construction, it will never have apcs itself.
    machine: Machine<F, RiscvAir<F>>,
    /// Cache of filled APC trace values, keyed by [`record_key`]. Populated by
    /// `generate_dependencies` (Phase 1) and consumed (read-and-removed) by `generate_trace_into`
    /// (Phase 2). This is what makes the record-in-chip synthetic record materialize *once*: both
    /// phases produce bit-identical rows from the same synth, so Phase 2 restores the Phase-1
    /// trace via `memcpy` instead of re-executing the invocations a second time. Values are the
    /// trace's Montgomery-form bytes viewed as `Vec<u32>` (`MontyField31` is `repr(transparent)`
    /// over `u32`). `Mutex` because `ApcChip` is shared via `Arc` across shard workers.
    cached_traces: Mutex<HashMap<([u32; 4], u64), Vec<u32>>>,
}

impl<F: PrimeField32> ApcChip<F> {
    pub fn new(apc: Arc<Sp1Apc<F>>, id: usize) -> Self {
        Self {
            id,
            name: format!("APC_{id}"),
            cached_apc: apc.into(),
            machine: RiscvAir::machine(),
            cached_traces: Mutex::new(HashMap::new()),
        }
    }

    pub fn apc(&self) -> &Arc<Sp1Apc<F>> {
        &self.cached_apc.apc
    }

    pub fn id(&self) -> usize {
        self.id
    }

    /// Record-in-chip: build a synthetic [`ExecutionRecord`] containing this APC's block events,
    /// regenerated by re-executing each captured `ApcInvocation` (in invocation order) into a
    /// fresh record. The instruction chips then generate their dummy traces from this synthetic
    /// record (via `included` / `generate_trace`) exactly as they did from the previously-carved
    /// `events.record`, producing bit-identical APC rows. Returns `None` when no invocations were
    /// captured for this APC id.
    fn b1_synthetic_record(&self, input: &ExecutionRecord) -> Option<ExecutionRecord> {
        let invocations = input.get_apc_invocations(self.id);
        if invocations.is_empty() {
            return None;
        }
        let program = input.program.clone();
        let nonce = input.public_values.proof_nonce;
        let opts = SP1CoreOpts::default();
        let mut synth = ExecutionRecord::new(program.clone(), nonce, input.global_dependencies_opt);
        for inv in invocations {
            // Replay directly into `synth` (no per-invocation ExecutionRecord alloc + append):
            // with many small blocks, that per-call overhead dominates trace generation.
            TracingVM::<SupervisorMode>::reexecute_apc_block_into(
                inv,
                program.clone(),
                opts.clone(),
                nonce,
                &mut synth,
            )
            .expect("record-in-chip: reexecute_apc_block_into failed");
        }
        Some(synth)
    }
}

impl<F: PrimeField32> BaseAir<F> for ApcChip<F> {
    fn width(&self) -> usize {
        self.cached_apc.width()
    }
}

impl<F: PrimeField32> MachineAir<F> for ApcChip<F> {
    // this may have to be changed
    type Record = ExecutionRecord;

    type Program = Program;

    fn name(&self) -> &str {
        &self.name
    }

    fn num_rows(&self, input: &Self::Record) -> Option<usize> {
        let num_apc_events = input.apc_event_count(self.id);
        let nb_rows = next_multiple_of_32(num_apc_events, input.fixed_log2_rows::<F, _>(self));
        Some(nb_rows)
    }

    fn generate_trace_into(
        &self,
        input: &Self::Record,
        _output: &mut Self::Record,
        buffer: &mut [std::mem::MaybeUninit<F>],
    ) {
        let event_count = input.apc_event_count(self.id);
        let trace_width = self.width();

        // Fast path: reuse the trace values cached by `generate_dependencies` (Phase 1). Both
        // phases produce bit-identical rows from the same synthetic record, so Phase 2 restores
        // them via memcpy instead of re-executing the captured invocations a second time. This is
        // what makes an APC block's events materialize only once (in Phase 1's synth).
        if let Some(cached) = self.cached_traces.lock().unwrap().remove(&record_key(input)) {
            let padding_start = event_count * trace_width;
            // Event rows come from `cached`; only the padding rows need zeroing.
            unsafe {
                core::ptr::write_bytes(
                    buffer[padding_start..].as_mut_ptr(),
                    0,
                    buffer.len() - padding_start,
                );
            }
            assert_eq!(std::mem::size_of::<F>(), std::mem::size_of::<u32>());
            assert_eq!(std::mem::align_of::<F>(), std::mem::align_of::<u32>());
            debug_assert_eq!(cached.len(), event_count * trace_width);
            unsafe {
                std::ptr::copy_nonoverlapping(
                    cached.as_ptr() as *const u8,
                    buffer.as_mut_ptr() as *mut u8,
                    cached.len() * std::mem::size_of::<u32>(),
                );
            }
            return;
        }

        // Fallback (cache miss, e.g. a deserialized record): regenerate the block events by
        // re-executing the captured invocations into a synthetic record, then source the
        // instruction chips' dummy traces from it (bit-identical to the carving path).
        let synth = self.b1_synthetic_record(input).expect("APC events not found");

        // Mapping from poly_id to contiguous index in apc
        let apc_poly_id_to_index = self
            .apc()
            .machine
            .main_columns()
            .enumerate()
            .map(|(index, c)| (c.id, index))
            .collect::<BTreeMap<_, _>>();

        // Get is_valid_index to manually fill with 1 for witness generation
        let is_valid_column =
            self.apc().machine.main_columns().find(|c| &*c.name == "is_valid").unwrap();
        let is_valid_index = apc_poly_id_to_index[&is_valid_column.id];

        // Get the AIR IDs for the original instructions.
        let original_instruction_air_ids = self
            .apc()
            .block
            .instructions()
            .map(|(_pc, instr)| {
                try_instruction_type_to_air_id(InstructionType::from(instr.0))
                    .expect("Invalid instruction as an original instruction in an APC: {instr.0:?}")
            })
            .collect::<Vec<_>>();

        // Only the block's own instruction airs are substituted into the APC row, so generate dummy
        // traces for exactly those. Filtering on `included(&synth)` alone would also materialize
        // full traces for helper airs the synth touches (memory / byte / range) that are never used
        // here — enormous on memory-heavy programs like RSP, and the record-in-chip OOM cause.
        let needed_air_ids: HashSet<RiscvAirId> =
            original_instruction_air_ids.iter().copied().collect();
        let chips_and_traces = self
            .machine
            .chips()
            .into_par_iter()
            .filter(|air| needed_air_ids.contains(&air.air.id()) && air.included(&synth))
            .map(|air| {
                let trace = air.generate_trace(&synth, &mut Default::default());
                (air.air.id(), trace)
            })
            .collect::<BTreeMap<_, _>>();

        // Map from AIR ID to number of occurrences
        let air_id_occurrences = original_instruction_air_ids.iter().counts();

        // Vec of dummy trace row offset by original instruction index
        let instruction_index_to_table_offset = original_instruction_air_ids
            .iter()
            .scan(HashMap::default(), |counts: &mut HashMap<RiscvAirId, usize>, air_id| {
                let count = counts.entry(*air_id).or_default();
                let current_count = *count;
                *count += 1;
                Some(current_count)
            })
            .collect::<Vec<_>>();

        // A vector of HashMap<dummy_trace_index, apc_trace_index> by instruction, empty HashMap if
        // none maps to apc
        let dummy_trace_index_to_apc_index_by_instruction: Vec<HashMap<usize, usize>> = self
            .apc()
            .subs
            .iter()
            .enumerate()
            .map(|(instruction_index, substitutions)| {
                // build a map only of the (dummy_index -> apc_index) pairs
                let mut map = HashMap::new();
                for sub in substitutions {
                    let Substitution { original_poly_index, apc_poly_id } = sub;
                    let apc_index = apc_poly_id_to_index.get(apc_poly_id).unwrap();
                    tracing::trace!("Mapping dummy_index {original_poly_index} to apc_index {apc_index} for instruction {instruction_index}");
                    map.insert(*original_poly_index, *apc_index);
                }
                tracing::trace!("Map for instruction {instruction_index}: {map:?}");
                map
            })
            .collect();

        assert_eq!(
            self.apc().block.instructions().count(),
            dummy_trace_index_to_apc_index_by_instruction.len()
        );

        // Zero only padding rows (event rows are fully written by the substitution loop).
        let padding_start = event_count * trace_width;
        unsafe {
            core::ptr::write_bytes(
                buffer[padding_start..].as_mut_ptr(),
                0,
                buffer.len() - padding_start,
            );
        }

        // Reinterpret buffer as initialized slice for filling.
        // Safety: padding rows are zeroed above; event rows are fully written by
        // substitutions (covering all main_columns) + the manual is_valid assignment.
        let trace_values = unsafe {
            std::slice::from_raw_parts_mut(buffer.as_mut_ptr().cast::<F>(), buffer.len())
        };

        // Fill in the trace values in parallel for each event row. Dummy slices are looked up
        // inline per row rather than materialized into a `Vec<Vec<&[F]>>` over all events.
        trace_values[..event_count * trace_width].par_chunks_mut(trace_width).enumerate().for_each(
            |(event_index, trace_row)| {
                for (instruction_index, (air_id, offset)) in original_instruction_air_ids
                    .iter()
                    .zip_eq(instruction_index_to_table_offset.iter())
                    .enumerate()
                {
                    let dummy_table = chips_and_traces.get(air_id).unwrap();
                    let dummy_width = dummy_table.width();
                    let occurrence_per_event = *air_id_occurrences.get(air_id).unwrap();
                    let start = (event_index * occurrence_per_event + offset) * dummy_width;
                    let dummy_slice = &dummy_table.values[start..start + dummy_width];
                    let map = &dummy_trace_index_to_apc_index_by_instruction[instruction_index];
                    // Only assign the values mapped into the APC (not the whole dummy row).
                    for (dummy_index, apc_index) in map.iter() {
                        trace_row[*apc_index] = dummy_slice[*dummy_index];
                    }
                }

                // Manually set is_valid column to 1
                trace_row[is_valid_index] = F::one();

                tracing::trace!("Final row: {trace_row:?}");
            },
        );
    }

    fn generate_dependencies(&self, input: &Self::Record, output: &mut Self::Record) {
        // Record-in-chip: regenerate this APC's block events into a synthetic record.
        // Because `generate_dependencies` is run during execution for all chips, it's not
        // guaranteed that there will be APC invocations at all.
        let Some(synth) = self.b1_synthetic_record(input) else {
            tracing::debug!(
                "No APC events found for APC ID during `generate_dependencies`: {}",
                self.id
            );
            return; // Early return because no dependencies to generate.
        };
        let event_count = input.apc_event_count(self.id);

        // Mapping from poly_id to contiguous index in apc
        let apc_poly_id_to_index = self
            .apc()
            .machine
            .main_columns()
            .enumerate()
            .map(|(index, c)| (c.id, index))
            .collect::<BTreeMap<_, _>>();

        // Get is_valid_index to manually fill with 1 for witness generation
        let is_valid_column =
            self.apc().machine.main_columns().find(|c| &*c.name == "is_valid").unwrap();
        let is_valid_index = apc_poly_id_to_index[&is_valid_column.id];

        // Get the AIR IDs for the original instructions.
        let original_instruction_air_ids = self
            .apc()
            .block
            .instructions()
            .map(|(_pc, instr)| {
                try_instruction_type_to_air_id(InstructionType::from(instr.0))
                    .expect("Invalid instruction as an original instruction in an APC: {instr.0:?}")
            })
            .collect::<Vec<_>>();

        // Only the block's own instruction airs are substituted into the APC row, so generate dummy
        // traces for exactly those. Filtering on `included(&synth)` alone would also materialize
        // full traces for helper airs the synth touches (memory / byte / range) that are never used
        // here — enormous on memory-heavy programs like RSP, and the record-in-chip OOM cause.
        let needed_air_ids: HashSet<RiscvAirId> =
            original_instruction_air_ids.iter().copied().collect();
        let chips_and_traces = self
            .machine
            .chips()
            .into_par_iter()
            .filter(|air| needed_air_ids.contains(&air.air.id()) && air.included(&synth))
            .map(|air| {
                let trace = air.generate_trace(&synth, &mut Default::default());
                (air.air.id(), trace)
            })
            .collect::<BTreeMap<_, _>>();

        // Map from AIR ID to number of occurrences
        let air_id_occurrences = original_instruction_air_ids.iter().counts();

        // Vec of dummy trace row offset by original instruction index
        let instruction_index_to_table_offset = original_instruction_air_ids
            .iter()
            .scan(HashMap::default(), |counts: &mut HashMap<RiscvAirId, usize>, air_id| {
                let count = counts.entry(*air_id).or_default();
                let current_count = *count;
                *count += 1;
                Some(current_count)
            })
            .collect::<Vec<_>>();

        // A vector of HashMap<dummy_trace_index, apc_trace_index> by instruction, empty HashMap if
        // none maps to apc
        let dummy_trace_index_to_apc_index_by_instruction: Vec<HashMap<usize, usize>> = self
            .apc()
            .subs
            .iter()
            .enumerate()
            .map(|(instruction_index, substitutions)| {
                // build a map only of the (dummy_index -> apc_index) pairs
                let mut map = HashMap::new();
                for sub in substitutions {
                    let Substitution { original_poly_index, apc_poly_id } = sub;
                    let apc_index = apc_poly_id_to_index.get(apc_poly_id).unwrap();
                    tracing::trace!("Mapping dummy_index {original_poly_index} to apc_index {apc_index} for instruction {instruction_index}");
                    map.insert(*original_poly_index, *apc_index);
                }
                tracing::trace!("Map for instruction {instruction_index}: {map:?}");
                map
            })
            .collect();

        assert_eq!(
            self.apc().block.instructions().count(),
            dummy_trace_index_to_apc_index_by_instruction.len()
        );

        // Allocate final trace values
        let trace_width = self.width();
        let mut trace_values = zeroed_f_vec(event_count * trace_width);

        // Fill in the trace values in parallel. Two allocations that were O(events) — a
        // `Vec<Vec<&[F]>>` of dummy slices, and a per-row `HashMap` of byte lookups collected into
        // a `Vec<HashMap>` — were the record-in-chip memory blowup on wide programs like RSP (this
        // OOM'd at ~62GB where the carving path fits in ~24GB). Both are gone: dummy slices are
        // looked up inline per row, and byte lookups accumulate into one map per chunk (~one per
        // thread) rather than one per event.
        let num_threads = std::thread::available_parallelism().map_or(16, |n| n.get());
        let chunk_rows = std::cmp::max(event_count.div_ceil(num_threads), 1);
        let byte_lookup_effects: Vec<HashMap<ByteLookupEvent, usize>> = trace_values
            .par_chunks_mut(chunk_rows * trace_width)
            .enumerate()
            .map(|(chunk_idx, trace_chunk)| {
                let mut byte_lookup_effect = HashMap::new();
                let chunk_start = chunk_idx * chunk_rows;
                for (local_idx, trace_row) in trace_chunk.chunks_mut(trace_width).enumerate() {
                    let event_index = chunk_start + local_idx;
                    for (instruction_index, (air_id, offset)) in original_instruction_air_ids
                        .iter()
                        .zip_eq(instruction_index_to_table_offset.iter())
                        .enumerate()
                    {
                        let dummy_table = chips_and_traces.get(air_id).unwrap();
                        let dummy_width = dummy_table.width();
                        let occurrence_per_event = *air_id_occurrences.get(air_id).unwrap();
                        let start = (event_index * occurrence_per_event + offset) * dummy_width;
                        let dummy_slice = &dummy_table.values[start..start + dummy_width];
                        let map = &dummy_trace_index_to_apc_index_by_instruction[instruction_index];
                        // Only assign the values mapped into the APC (not the whole dummy row).
                        for (dummy_index, apc_index) in map.iter() {
                            trace_row[*apc_index] = dummy_slice[*dummy_index];
                        }
                    }

                    // Manually set is_valid column to 1
                    trace_row[is_valid_index] = F::one();

                    tracing::trace!("Final row: {trace_row:?}");

                    // Replay side effects as events
                    // Only need to do this for byte lookup bus, as other buses are implicitly balanced
                    // via main trace values rather than via events
                    let evaluator = RowEvaluator::new(trace_row, Some(&apc_poly_id_to_index));

                    // Accumulate byte-lookup effects into this chunk's shared map.
                    for bus_interaction in
                        self.apc().machine.bus_interactions.iter().filter(|bus_interaction| {
                            bus_interaction.id == InteractionKind::Byte as u64
                        })
                    {
                        let mult = evaluator.eval_expr(&bus_interaction.mult).as_canonical_u32();
                        let mut args = bus_interaction
                            .args
                            .iter()
                            .map(|arg| evaluator.eval_expr(arg).as_canonical_u32());
                        let opcode = args.next().unwrap() as usize;
                        let a = args.next().unwrap() as u16;
                        let b = args.next().unwrap() as u8;
                        let c = args.next().unwrap() as u8;
                        assert!(args.next().is_none());

                        // byte lookup
                        *byte_lookup_effect
                            .entry(ByteLookupEvent {
                                opcode: match opcode {
                                    o if o == ByteOpcode::AND as usize => ByteOpcode::AND,
                                    o if o == ByteOpcode::OR as usize => ByteOpcode::OR,
                                    o if o == ByteOpcode::XOR as usize => ByteOpcode::XOR,
                                    o if o == ByteOpcode::U8Range as usize => ByteOpcode::U8Range,
                                    o if o == ByteOpcode::LTU as usize => ByteOpcode::LTU,
                                    o if o == ByteOpcode::MSB as usize => ByteOpcode::MSB,
                                    o if o == ByteOpcode::Range as usize => ByteOpcode::Range,
                                    _ => unreachable!("Unexpected byte lookup Opcode: {}", opcode),
                                },
                                a,
                                b,
                                c,
                            })
                            .or_insert(0) += mult as usize;
                    }
                }
                byte_lookup_effect
            })
            .collect::<Vec<_>>();

        // Apply effects after parallel execution
        for byte_lookup_effect in byte_lookup_effects {
            for (event, count) in byte_lookup_effect.iter() {
                *output.byte_lookups.entry(*event).or_insert(0) += *count as usize;
            }
        }

        // Cache the filled trace values (Montgomery-form `u32` bytes) so `generate_trace_into`
        // restores them via memcpy instead of rebuilding the synthetic record in Phase 2. Keyed
        // off `input` (the shard record); `output` is a per-chip default whose key would be zero
        // and collide across chips.
        assert_eq!(std::mem::size_of::<F>(), std::mem::size_of::<u32>());
        assert_eq!(std::mem::align_of::<F>(), std::mem::align_of::<u32>());
        let mut cached: Vec<u32> = vec![0u32; trace_values.len()];
        unsafe {
            std::ptr::copy_nonoverlapping(
                trace_values.as_ptr() as *const u8,
                cached.as_mut_ptr() as *mut u8,
                trace_values.len() * std::mem::size_of::<u32>(),
            );
        }
        self.cached_traces.lock().unwrap().insert(record_key(input), cached);
    }

    fn included(&self, shard: &Self::Record) -> bool {
        shard.has_apc_events(self.id)
    }

    fn customize_program(&self, program: Self::Program) -> Self::Program {
        let range = ApcRange::new(
            ((self.apc().block.try_as_basic_block().unwrap().start_pc - program.pc_base)
                / Sp1Instruction::pc_step() as u64) as usize,
            self.apc().block.instructions().count(),
        );
        let apc = sp1_core_executor::Apc::new(
            range,
            self.cached_apc.width() as u64,
            self.apc().optimistic_constraints.clone(),
        );
        program.add_apc(apc)
    }
}

impl<AB: SP1AirBuilder + PairBuilder + MessageBuilder<AirInteraction<AB::Expr>>> Air<AB>
    for ApcChip<AB::F>
where
    AB::F: PrimeField32,
{
    fn eval(&self, builder: &mut AB) {
        let main = builder.main();
        let witnesses = main.row_slice(0);

        let witness_values: BTreeMap<u64, AB::Var> = self
            .cached_apc
            .columns
            .iter()
            .map(|c| c.id)
            .zip_eq(witnesses.iter().cloned())
            .collect();

        let witness_evaluator = WitnessEvaluator::<AB>::new(&witness_values);

        for constraint in &self.cached_apc.apc.machine().constraints {
            let e = witness_evaluator.eval_expr(&constraint.expr);
            builder.assert_zero(e);
        }

        for interaction in &self.cached_apc.apc.machine().bus_interactions {
            let mult = witness_evaluator.eval_expr(&interaction.mult);
            let args =
                interaction.args.iter().map(|arg| witness_evaluator.eval_expr(arg)).collect_vec();

            // All instruction AIRs only use the four buses below.
            let interaction_kind = match interaction.id {
                id if id == InteractionKind::Memory as u64 => InteractionKind::Memory,
                id if id == InteractionKind::Program as u64 => InteractionKind::Program,
                id if id == InteractionKind::Byte as u64 => InteractionKind::Byte,
                id if id == InteractionKind::State as u64 => InteractionKind::State,
                id if id == InteractionKind::InstructionFetch as u64 => {
                    InteractionKind::InstructionFetch
                }
                _ => unreachable!("Unexpected bus ID: {}", interaction.id),
            };

            let air_interaction = AirInteraction::new(args, mult, interaction_kind);

            // We only need to send, because receive is just send with negative multiplicity.
            builder.send(air_interaction, InteractionScope::Local);
        }
    }
}

pub struct WitnessEvaluator<'a, AB: AirBuilder> {
    pub witness: &'a BTreeMap<u64, AB::Var>,
}

impl<'a, AB: AirBuilder> WitnessEvaluator<'a, AB> {
    pub fn new(witness: &'a BTreeMap<u64, AB::Var>) -> Self {
        Self { witness }
    }
}

impl<AB: AirBuilder> WitnessEvaluator<'_, AB> {
    fn eval_const(&self, c: AB::F) -> AB::Expr {
        c.into()
    }

    fn eval_var(&self, symbolic_var: AlgebraicReference) -> AB::Expr {
        (*self.witness.get(&(symbolic_var.id as u64)).unwrap()).into()
    }

    fn eval_expr(&self, algebraic_expr: &AlgebraicExpression<AB::F>) -> AB::Expr {
        match algebraic_expr {
            AlgebraicExpression::Number(n) => self.eval_const(*n),
            AlgebraicExpression::BinaryOperation(binary) => match binary.op {
                AlgebraicBinaryOperator::Add => {
                    self.eval_expr(&binary.left) + self.eval_expr(&binary.right)
                }
                AlgebraicBinaryOperator::Sub => {
                    self.eval_expr(&binary.left) - self.eval_expr(&binary.right)
                }
                AlgebraicBinaryOperator::Mul => {
                    self.eval_expr(&binary.left) * self.eval_expr(&binary.right)
                }
            },
            AlgebraicExpression::UnaryOperation(unary) => match unary.op {
                AlgebraicUnaryOperator::Minus => -self.eval_expr(&unary.expr),
            },
            AlgebraicExpression::Reference(var) => self.eval_var(var.clone()),
        }
    }
}

pub struct RowEvaluator<'a, F: PrimeField32> {
    pub row: &'a [F],
    pub witness_id_to_index: Option<&'a BTreeMap<u64, usize>>,
}

impl<'a, F: PrimeField32> RowEvaluator<'a, F> {
    pub fn new(row: &'a [F], witness_id_to_index: Option<&'a BTreeMap<u64, usize>>) -> Self {
        Self { row, witness_id_to_index }
    }

    fn eval_expr(&self, algebraic_expr: &AlgebraicExpression<F>) -> F {
        match algebraic_expr {
            AlgebraicExpression::Number(n) => self.eval_const(*n),
            AlgebraicExpression::BinaryOperation(binary) => match binary.op {
                AlgebraicBinaryOperator::Add => {
                    self.eval_expr(&binary.left) + self.eval_expr(&binary.right)
                }
                AlgebraicBinaryOperator::Sub => {
                    self.eval_expr(&binary.left) - self.eval_expr(&binary.right)
                }
                AlgebraicBinaryOperator::Mul => {
                    self.eval_expr(&binary.left) * self.eval_expr(&binary.right)
                }
            },
            AlgebraicExpression::UnaryOperation(unary) => match unary.op {
                AlgebraicUnaryOperator::Minus => -self.eval_expr(&unary.expr),
            },
            AlgebraicExpression::Reference(var) => self.eval_var(var.clone()),
        }
    }

    fn eval_const(&self, c: F) -> F {
        c
    }

    fn eval_var(&self, algebraic_var: AlgebraicReference) -> F {
        let index = if let Some(witness_id_to_index) = self.witness_id_to_index {
            witness_id_to_index[&(algebraic_var.id)]
        } else {
            algebraic_var.id as usize
        };
        self.row[index]
    }
}
