[package]
name = "bn254-add-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
common-test-utils = { path = "../common" }
sp1-lib = { path = "../../../../crates/zkvm/lib" }
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
sp1-curves = { path = "../../../../crates/curves" }
